INSERT INTO warbands (name, faction_name, number_of_fighters, season)
SELECT name, faction_name, number_of_fighters, season
FROM (VALUES
          ('Steelheart’s Champions', 'Order', 3, 'Shadespire'),
          ('Garrek''s Reavers', 'Chaos', 5, 'Shadespire'),
          ('Sepulchral Guard', 'Death', 7, 'Shadespire'),
          ('Ironskull’s Boyz', 'Destruction', 4, 'Shadespire'),
          ('The Chosen Axes', 'Order', 4, 'Shadespire'),
          ('Spiteclaw’s Swarm', 'Chaos', 5, 'Shadespire'),
          ('The Farstriders', 'Order', 3, 'Shadespire'),
          ('Magore’s Fiends', 'Chaos', 4, 'Shadespire'),
          ('Stormsire''s Cursebreakers', 'Order', 3, 'Nightvault'),
          ('Thorns of the Briar Queen', 'Death', 7, 'Nightvault'),
          ('The Eyes of the Nine', 'Chaos', 6, 'Nightvault'),
          ('Zarbag''s Gitz', 'Destruction', 9, 'Nightvault'),
          ('Godsworn Hunt', 'Chaos', 6, 'Nightvault'),
          ('Mollog’s Mob', 'Destruction', 4, 'Nightvault'),
          ('Thundrik’s Profiteers', 'Order', 5, 'Nightvault'),
          ('Ylthari’s Guardians', 'Order', 4, 'Nightvault'),
          ('Grashrak’s Despoilers', 'Destruction', 6, 'Beastgrave'),
          ('Skaeth’s Wild Hunt', 'Order', 5, 'Beastgrave'),
          ('The Grymwatch', 'Death', 7, 'Beastgrave'),
          ('Rippa’s Snarlfangs', 'Destruction', 3, 'Beastgrave'),
          ('Ironsoul’s Condemners', 'Order', 3, 'Beastgrave'),
          ('Lady Harrow’s Mournflight', 'Death', 4, 'Beastgrave'),
          ('The Wurmspat', 'Chaos', 3, 'Beastgrave'),
          ('Hrothgorn’s Mantrappers', 'Destruction', 5, 'Beastgrave'),
          ('Morgwaeth’s Blade Coven', 'Order', 5, 'Beastgrave'),
          ('Morgok''s Krushas', 'Destruction', 3, 'Beastgrave'),
          ('Myari’s Purifiers', 'Order', 4, 'Direchasm'),
          ('The Dread Pageant', 'Chaos', 4, 'Direchasm'),
          ('Khagra''s Ravagers', 'Chaos', 4, 'Direchasm'),
          ('Starblood Stalkers', 'Order', 6, 'Direchasm'),
          ('Crimson Court', 'Death', 4, 'Direchasm'),
          ('Storm of Celestus', 'Order', 4, 'Direchasm'),
          ('Drepur’s Wraithcreepers', 'Death', 4, 'Direchasm'),
          ('Hedkrakka’s Madmob', 'Destruction', 4, 'Direchasm'),
          ('Kainan’s Reapers', 'Death', 6, 'Direchasm'),
          ('Elathain’s Soulraid', 'Order', 5, 'Direchasm'),
          ('Xandire’s Truthseekers', 'Order', 4, 'Harrowdeep'),
          ('Da Kunnin’ Krew', 'Destruction', 5, 'Harrowdeep'),
          ('Blackpowder’s Buccaneers', 'Destruction', 5, 'Harrowdeep'),
          ('The Exiled Dead', 'Death', 7, 'Harrowdeep'),
          ('The Shadeborn', 'Order', 4, 'Nethermaze'),
          ('Skittershank’s Clawpack', 'Chaos', 5, 'Nethermaze'),
          ('Hexbane’s Hunters', 'Order', 6, 'Nethermaze'),
          ('Gorechosen of Dromm', 'Chaos', 3, 'Nethermaze'),
          ('Gnarlspirit Pack', 'Chaos', 4, 'Gnarlwood'),
          ('Sons of Velmorn', 'Death', 5, 'Gnarlwood'),
          ('Grinkrak’s Looncourt', 'Destruction', 7, 'Gnarlwood'),
          ('Gryselle’s Arenai', 'Order', 5, 'Gnarlwood'),
          ('Domitan’s Stormcoven', 'Order', 3, 'Wyrdhollow'),
          ('Ephilim’s Pandaemonium', 'Chaos', 5, 'Wyrdhollow'),
          ('The Headmen’s Curse', 'Death', 4, 'Wyrdhollow'),
          ('Skabbik’s Plaguepack', 'Chaos', 6, 'Wyrdhollow'),
          ('The Thricefold Discord', 'Chaos', 3, 'Deathgorge'),
          ('Cyreni’s Razors', 'Order', 4, 'Deathgorge'),
          ('Daggok’s Stab-Ladz', 'Destruction', 4, 'Deathgorge'),
          ('Zondara’s Gravebreakers', 'Death', 5, 'Deathgorge'),
          ('Brethren of the Bolt', 'Order', 5, 'Wintermaw'),
          ('The Skinnerkin', 'Death', 5, 'Wintermaw')
     ) AS t (name, faction_name, number_of_fighters, season)
WHERE NOT EXISTS (SELECT 1 FROM warbands WHERE name = t.name);
